### ISSUE TITLE
Update Hackage Cabal metadata to reflect current `base` bound

### ISSUE THREAD

**Issue by jhenahan** [serokell/nyan-interpolation#20]
# Clarification and motivation

Today, the repository advertises support for `base <4.17`, but Hackage still reports `base <4.15`, meaning that a successful build plan requires some intervention on the consumer end for, e.g., GHC 9.2.4.

# Acceptance criteria

- Hackage reflects the current version bounds
- It is possible to create a build plan for at least GHC 9.2.x that includes `nyan-interpolation` without additional configuration

**Comment by Martoon-00** [comment]
I'm really sorry for the long delay. Now versions on hackage should have the updated boundaries.

On this part:
> It is possible to create a build plan for at least GHC 9.2.x that includes nyan-interpolation without additional configuration

I assume this also involves including the package into LTS, so that there is no need in `extra-deps`?

I'm a bit reluctant to do it right now, since this package is not in its final state yet. But if you want it to be included in LTS, please re-open this issue.
